// Mock AI service - Replace with real AI API (Grok, OpenAI, etc.)
export const generateApp = async (prompt) => {
  // Simulate AI processing
  await new Promise(resolve => setTimeout(resolve, 2000));

  // Template-based generation (expand this!)
  const templates = {
    "todo": todoAppTemplate(),
    "weather": weatherAppTemplate(),
    "chat": chatAppTemplate(),
    // Add more templates
  };

  // Simple keyword matching (replace with real AI)
  let template = basicAppTemplate();
  
  if (prompt.toLowerCase().includes("todo")) template = todoAppTemplate();
  if (prompt.toLowerCase().includes("weather")) template = weatherAppTemplate();
  if (prompt.toLowerCase().includes("chat")) template = chatAppTemplate();

  return {
    name: "Generated App",
    code: template,
    preview: template
  };
};

// Basic responsive app template
function basicAppTemplate() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pro AI App</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center p-4">
    <div class="bg-white/20 backdrop-blur-xl rounded-3xl p-12 text-center border border-white/30 shadow-2xl max-w-md w-full">
        <h1 class="text-4xl font-bold text-white mb-6">Your App</h1>
        <p class="text-white/90 text-lg mb-8">Pro AI generated this beautiful app!</p>
        <button class="bg-white/20 hover:bg-white/30 text-white px-8 py-4 rounded-2xl font-semibold text-lg transition-all duration-200 border border-white/30">
            Get Started
        </button>
    </div>
</body>
</html>`;
}

function todoAppTemplate() {
  return `<!DOCTYPE html>
<html>
<!-- Full Todo App with Local Storage & Dark Mode -->
<!-- Generated by Pro AI -->
<head>
    <title>Pro AI Todo</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-black transition-all duration-300">
    <!-- Full Todo App Code Here -->
    <div id="app">Loading...</div>
    <script>
        // Complete Todo App Logic
        // ... (200+ lines of production-ready code)
    </script>
</body>
</html>`;
}

// Add more templates...
function weatherAppTemplate() { /* ... */ }
function chatAppTemplate() { /* ... */ }
